spring.datasource.url=jdbc:postgresql://localhost:15432/tolo_idp
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=tolo_idp
spring.datasource.password=tolo_idp
spring.flyway.locations=classpath:db/postgresql

tolo-idp.issuer=http://localhost:18080
tolo-idp.rate-limit.redis.uri=redis://localhost:16379
tolo-idp.seed.enabled=true
tolo-idp.jwk.allow-ephemeral=true
