spring.application.name=tolo-idp
spring.datasource.url=jdbc:h2:mem:tolo-idp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.flyway.enabled=true
spring.h2.console.enabled=false
logging.level.org.springframework.security=INFO
spring.cloud.gcp.core.enabled=false

tolo-idp.issuer=http://localhost:8080
tolo-idp.resource.allowed-hosts=api.example.com
tolo-idp.relation.base-url=http://localhost:8081
tolo-idp.relation.cache.ttl=5m
tolo-idp.jwk.allow-ephemeral=true
